apiVersion: apps/v1
kind: Deployment
metadata:
  name: proof-sdk
  namespace: proof
spec:
  template:
    spec:
      containers:
        - name: proof-sdk
          envFrom:
            - configMapRef:
                name: proof-sdk-config
            - secretRef:
                name: stg-proof-secrets
